package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * AsistenciaInstitucion generated by hbm2java
 */
public class AsistenciaInstitucion  implements java.io.Serializable {


     private int plantel;
     private Plantel plantel_1;
     private char orientIndiv;
     private char orientFamil;
     private char programas;
     private String cuales;

    public AsistenciaInstitucion() {
    }

    public AsistenciaInstitucion(int plantel, Plantel plantel_1, char orientIndiv, char orientFamil, char programas, String cuales) {
       this.plantel = plantel;
       this.plantel_1 = plantel_1;
       this.orientIndiv = orientIndiv;
       this.orientFamil = orientFamil;
       this.programas = programas;
       this.cuales = cuales;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public Plantel getPlantel_1() {
        return this.plantel_1;
    }
    
    public void setPlantel_1(Plantel plantel_1) {
        this.plantel_1 = plantel_1;
    }
    public char getOrientIndiv() {
        return this.orientIndiv;
    }
    
    public void setOrientIndiv(char orientIndiv) {
        this.orientIndiv = orientIndiv;
    }
    public char getOrientFamil() {
        return this.orientFamil;
    }
    
    public void setOrientFamil(char orientFamil) {
        this.orientFamil = orientFamil;
    }
    public char getProgramas() {
        return this.programas;
    }
    
    public void setProgramas(char programas) {
        this.programas = programas;
    }
    public String getCuales() {
        return this.cuales;
    }
    
    public void setCuales(String cuales) {
        this.cuales = cuales;
    }




}


