package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * Charla generated by hbm2java
 */
public class Charla  implements java.io.Serializable {


     private CharlaId id;
     private EstudianteServCom estudianteServCom;
     private Plantel plantel;
     private int horas;

    public Charla() {
    }

    public Charla(CharlaId id, EstudianteServCom estudianteServCom, Plantel plantel, int horas) {
       this.id = id;
       this.estudianteServCom = estudianteServCom;
       this.plantel = plantel;
       this.horas = horas;
    }
   
    public CharlaId getId() {
        return this.id;
    }
    
    public void setId(CharlaId id) {
        this.id = id;
    }
    public EstudianteServCom getEstudianteServCom() {
        return this.estudianteServCom;
    }
    
    public void setEstudianteServCom(EstudianteServCom estudianteServCom) {
        this.estudianteServCom = estudianteServCom;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public int getHoras() {
        return this.horas;
    }
    
    public void setHoras(int horas) {
        this.horas = horas;
    }




}


