package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.util.Date;

/**
 * CharlaId generated by hbm2java
 */
public class CharlaId  implements java.io.Serializable {


     private String carnet;
     private int plantel;
     private Date fecha;

    public CharlaId() {
    }

    public CharlaId(String carnet, int plantel, Date fecha) {
       this.carnet = carnet;
       this.plantel = plantel;
       this.fecha = fecha;
    }
   
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CharlaId) ) return false;
		 CharlaId castOther = ( CharlaId ) other; 
         
		 return ( (this.getCarnet()==castOther.getCarnet()) || ( this.getCarnet()!=null && castOther.getCarnet()!=null && this.getCarnet().equals(castOther.getCarnet()) ) )
 && (this.getPlantel()==castOther.getPlantel())
 && ( (this.getFecha()==castOther.getFecha()) || ( this.getFecha()!=null && castOther.getFecha()!=null && this.getFecha().equals(castOther.getFecha()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getCarnet() == null ? 0 : this.getCarnet().hashCode() );
         result = 37 * result + this.getPlantel();
         result = 37 * result + ( getFecha() == null ? 0 : this.getFecha().hashCode() );
         return result;
   }   


}


