package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * DaniosInstitucion generated by hbm2java
 */
public class DaniosInstitucion  implements java.io.Serializable {


     private int plantel;
     private Plantel plantel_1;
     private char hechosViolentos;
     private Serializable tipoDanio;

    public DaniosInstitucion() {
    }

	
    public DaniosInstitucion(int plantel, Plantel plantel_1, char hechosViolentos) {
        this.plantel = plantel;
        this.plantel_1 = plantel_1;
        this.hechosViolentos = hechosViolentos;
    }
    public DaniosInstitucion(int plantel, Plantel plantel_1, char hechosViolentos, Serializable tipoDanio) {
       this.plantel = plantel;
       this.plantel_1 = plantel_1;
       this.hechosViolentos = hechosViolentos;
       this.tipoDanio = tipoDanio;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public Plantel getPlantel_1() {
        return this.plantel_1;
    }
    
    public void setPlantel_1(Plantel plantel_1) {
        this.plantel_1 = plantel_1;
    }
    public char getHechosViolentos() {
        return this.hechosViolentos;
    }
    
    public void setHechosViolentos(char hechosViolentos) {
        this.hechosViolentos = hechosViolentos;
    }
    public Serializable getTipoDanio() {
        return this.tipoDanio;
    }
    
    public void setTipoDanio(Serializable tipoDanio) {
        this.tipoDanio = tipoDanio;
    }




}


