package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * EstudianteServCom generated by hbm2java
 */
public class EstudianteServCom  implements java.io.Serializable {


     private String carnet;
     private int cedula;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private int numeroTotalHoras;
     private Set<Charla> charlas = new HashSet<Charla>(0);

    public EstudianteServCom() {
    }

	
    public EstudianteServCom(String carnet, int cedula, String primerNombre, String primerApellido, int numeroTotalHoras) {
        this.carnet = carnet;
        this.cedula = cedula;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.numeroTotalHoras = numeroTotalHoras;
    }
    public EstudianteServCom(String carnet, int cedula, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, int numeroTotalHoras, Set<Charla> charlas) {
       this.carnet = carnet;
       this.cedula = cedula;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.numeroTotalHoras = numeroTotalHoras;
       this.charlas = charlas;
    }
   
    public String getCarnet() {
        return this.carnet;
    }
    
    public void setCarnet(String carnet) {
        this.carnet = carnet;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public int getNumeroTotalHoras() {
        return this.numeroTotalHoras;
    }
    
    public void setNumeroTotalHoras(int numeroTotalHoras) {
        this.numeroTotalHoras = numeroTotalHoras;
    }
    public Set<Charla> getCharlas() {
        return this.charlas;
    }
    
    public void setCharlas(Set<Charla> charlas) {
        this.charlas = charlas;
    }




}


