package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.math.BigDecimal;

/**
 * EstudianteBachillerato generated by hbm2java
 */
public class EstudianteBachillerato  implements java.io.Serializable {


     private String usuario;
     private PerfilUsuario perfilUsuario;
     private Plantel plantel;
     private char sexo;
     private BigDecimal promNotas;
     private String carrera1;
     private String carrera2;
     private String carrera3;
     private String status;

    public EstudianteBachillerato() {
    }

    public EstudianteBachillerato(String usuario, PerfilUsuario perfilUsuario, Plantel plantel, char sexo, BigDecimal promNotas, String carrera1, String carrera2, String carrera3, String status) {
       this.usuario = usuario;
       this.perfilUsuario = perfilUsuario;
       this.plantel = plantel;
       this.sexo = sexo;
       this.promNotas = promNotas;
       this.carrera1 = carrera1;
       this.carrera2 = carrera2;
       this.carrera3 = carrera3;
       this.status = status;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public PerfilUsuario getPerfilUsuario() {
        return this.perfilUsuario;
    }
    
    public void setPerfilUsuario(PerfilUsuario perfilUsuario) {
        this.perfilUsuario = perfilUsuario;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public BigDecimal getPromNotas() {
        return this.promNotas;
    }
    
    public void setPromNotas(BigDecimal promNotas) {
        this.promNotas = promNotas;
    }
    public String getCarrera1() {
        return this.carrera1;
    }
    
    public void setCarrera1(String carrera1) {
        this.carrera1 = carrera1;
    }
    public String getCarrera2() {
        return this.carrera2;
    }
    
    public void setCarrera2(String carrera2) {
        this.carrera2 = carrera2;
    }
    public String getCarrera3() {
        return this.carrera3;
    }
    
    public void setCarrera3(String carrera3) {
        this.carrera3 = carrera3;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }




}


