package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * MencionPlantelId generated by hbm2java
 */
public class MencionPlantelId  implements java.io.Serializable {


     private int plantel;
     private String mencion;

    public MencionPlantelId() {
    }

    public MencionPlantelId(int plantel, String mencion) {
       this.plantel = plantel;
       this.mencion = mencion;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public String getMencion() {
        return this.mencion;
    }
    
    public void setMencion(String mencion) {
        this.mencion = mencion;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof MencionPlantelId) ) return false;
		 MencionPlantelId castOther = ( MencionPlantelId ) other; 
         
		 return (this.getPlantel()==castOther.getPlantel())
 && ( (this.getMencion()==castOther.getMencion()) || ( this.getMencion()!=null && castOther.getMencion()!=null && this.getMencion().equals(castOther.getMencion()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getPlantel();
         result = 37 * result + ( getMencion() == null ? 0 : this.getMencion().hashCode() );
         return result;
   }   


}


