package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * MencionPlantel generated by hbm2java
 */
public class MencionPlantel  implements java.io.Serializable {


     private MencionPlantelId id;
     private Plantel plantel;

    public MencionPlantel() {
    }

    public MencionPlantel(MencionPlantelId id, Plantel plantel) {
       this.id = id;
       this.plantel = plantel;
    }
   
    public MencionPlantelId getId() {
        return this.id;
    }
    
    public void setId(MencionPlantelId id) {
        this.id = id;
    }
    public Plantel getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(Plantel plantel) {
        this.plantel = plantel;
    }




}


