package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * PerfilUsuario generated by hbm2java
 */
public class PerfilUsuario  implements java.io.Serializable {


     private String usuario;
     private Usuario usuario_1;
     private int cedula;
     private String primerNombre;
     private String segundoNombre;
     private String primerApellido;
     private String segundoApellido;
     private String email;
     private char esSuperusuario;
     private Set<TelefonoU> telefonoUs = new HashSet<TelefonoU>(0);
     private Set<EstudianteBachillerato> estudianteBachilleratos = new HashSet<EstudianteBachillerato>(0);

    public PerfilUsuario() {
    }

	
    public PerfilUsuario(String usuario, Usuario usuario_1, int cedula, String primerNombre, String primerApellido, String email, char esSuperusuario) {
        this.usuario = usuario;
        this.usuario_1 = usuario_1;
        this.cedula = cedula;
        this.primerNombre = primerNombre;
        this.primerApellido = primerApellido;
        this.email = email;
        this.esSuperusuario = esSuperusuario;
    }
    public PerfilUsuario(String usuario, Usuario usuario_1, int cedula, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String email, char esSuperusuario, Set<TelefonoU> telefonoUs, Set<EstudianteBachillerato> estudianteBachilleratos) {
       this.usuario = usuario;
       this.usuario_1 = usuario_1;
       this.cedula = cedula;
       this.primerNombre = primerNombre;
       this.segundoNombre = segundoNombre;
       this.primerApellido = primerApellido;
       this.segundoApellido = segundoApellido;
       this.email = email;
       this.esSuperusuario = esSuperusuario;
       this.telefonoUs = telefonoUs;
       this.estudianteBachilleratos = estudianteBachilleratos;
    }
   
    public String getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(String usuario) {
        this.usuario = usuario;
    }
    public Usuario getUsuario_1() {
        return this.usuario_1;
    }
    
    public void setUsuario_1(Usuario usuario_1) {
        this.usuario_1 = usuario_1;
    }
    public int getCedula() {
        return this.cedula;
    }
    
    public void setCedula(int cedula) {
        this.cedula = cedula;
    }
    public String getPrimerNombre() {
        return this.primerNombre;
    }
    
    public void setPrimerNombre(String primerNombre) {
        this.primerNombre = primerNombre;
    }
    public String getSegundoNombre() {
        return this.segundoNombre;
    }
    
    public void setSegundoNombre(String segundoNombre) {
        this.segundoNombre = segundoNombre;
    }
    public String getPrimerApellido() {
        return this.primerApellido;
    }
    
    public void setPrimerApellido(String primerApellido) {
        this.primerApellido = primerApellido;
    }
    public String getSegundoApellido() {
        return this.segundoApellido;
    }
    
    public void setSegundoApellido(String segundoApellido) {
        this.segundoApellido = segundoApellido;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public char getEsSuperusuario() {
        return this.esSuperusuario;
    }
    
    public void setEsSuperusuario(char esSuperusuario) {
        this.esSuperusuario = esSuperusuario;
    }
    public Set<TelefonoU> getTelefonoUs() {
        return this.telefonoUs;
    }
    
    public void setTelefonoUs(Set<TelefonoU> telefonoUs) {
        this.telefonoUs = telefonoUs;
    }
    public Set<EstudianteBachillerato> getEstudianteBachilleratos() {
        return this.estudianteBachilleratos;
    }
    
    public void setEstudianteBachilleratos(Set<EstudianteBachillerato> estudianteBachilleratos) {
        this.estudianteBachilleratos = estudianteBachilleratos;
    }




}


