package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Plantel generated by hbm2java
 */
public class Plantel  implements java.io.Serializable {


     private int idPlantel;
     private String nombrePlantel;
     private String tipoInstitucion;
     private int distritoEscolar;
     private String direccion;
     private String emailPlantel;
     private String tlfPlantel;
     private String faxPlantel;
     private String nombreDirector;
     private String emailDirector;
     private String telfHabDirector;
     private String telfCelDirector;
     private String nombreCoordPio;
     private String emailCoordPio;
     private String telfHabCoordPio;
     private String telfCelCoordPio;
     private Set<ObsAA> obsAAs = new HashSet<ObsAA>(0);
     private Set<MencionPlantel> mencionPlantels = new HashSet<MencionPlantel>(0);
     private Set<SituacionEmbarazos> situacionEmbarazoses = new HashSet<SituacionEmbarazos>(0);
     private Set<AsistenciaInstitucion> asistenciaInstitucions = new HashSet<AsistenciaInstitucion>(0);
     private Set<ProgramasOrPs> programasOrPses = new HashSet<ProgramasOrPs>(0);
     private Set<Charla> charlas = new HashSet<Charla>(0);
     private Set<ServiciosPlantel> serviciosPlantels = new HashSet<ServiciosPlantel>(0);
     private Set<EstudianteBachillerato> estudianteBachilleratos = new HashSet<EstudianteBachillerato>(0);
     private Set<DaniosInstitucion> daniosInstitucions = new HashSet<DaniosInstitucion>(0);

    public Plantel() {
    }

	
    public Plantel(int idPlantel, String nombrePlantel, String tipoInstitucion, int distritoEscolar, String direccion, String nombreDirector, String nombreCoordPio) {
        this.idPlantel = idPlantel;
        this.nombrePlantel = nombrePlantel;
        this.tipoInstitucion = tipoInstitucion;
        this.distritoEscolar = distritoEscolar;
        this.direccion = direccion;
        this.nombreDirector = nombreDirector;
        this.nombreCoordPio = nombreCoordPio;
    }
    
    public Plantel(int idPlantel, String nombrePlantel, String tipoInstitucion, int distritoEscolar, String direccion, String emailPlantel, String tlfPlantel, String faxPlantel, String nombreDirector, String emailDirector, String telfHabDirector, String telfCelDirector, String nombreCoordPio, String emailCoordPio, String telfHabCoordPio, String telfCelCoordPio) {
       this.idPlantel = idPlantel;
       this.nombrePlantel = nombrePlantel;
       this.tipoInstitucion = tipoInstitucion;
       this.distritoEscolar = distritoEscolar;
       this.direccion = direccion;
       this.emailPlantel = emailPlantel;
       this.tlfPlantel = tlfPlantel;
       this.faxPlantel = faxPlantel;
       this.nombreDirector = nombreDirector;
       this.emailDirector = emailDirector;
       this.telfHabDirector = telfHabDirector;
       this.telfCelDirector = telfCelDirector;
       this.nombreCoordPio = nombreCoordPio;
       this.emailCoordPio = emailCoordPio;
       this.telfHabCoordPio = telfHabCoordPio;
       this.telfCelCoordPio = telfCelCoordPio;
    }
    
    public Plantel(int idPlantel, String nombrePlantel, String tipoInstitucion, int distritoEscolar, String direccion, String emailPlantel, String tlfPlantel, String faxPlantel, String nombreDirector, String emailDirector, String telfHabDirector, String telfCelDirector, String nombreCoordPio, String emailCoordPio, String telfHabCoordPio, String telfCelCoordPio, Set<ObsAA> obsAAs, Set<MencionPlantel> mencionPlantels, Set<SituacionEmbarazos> situacionEmbarazoses, Set<AsistenciaInstitucion> asistenciaInstitucions, Set<ProgramasOrPs> programasOrPses, Set<Charla> charlas, Set<ServiciosPlantel> serviciosPlantels, Set<EstudianteBachillerato> estudianteBachilleratos, Set<DaniosInstitucion> daniosInstitucions) {
       this.idPlantel = idPlantel;
       this.nombrePlantel = nombrePlantel;
       this.tipoInstitucion = tipoInstitucion;
       this.distritoEscolar = distritoEscolar;
       this.direccion = direccion;
       this.emailPlantel = emailPlantel;
       this.tlfPlantel = tlfPlantel;
       this.faxPlantel = faxPlantel;
       this.nombreDirector = nombreDirector;
       this.emailDirector = emailDirector;
       this.telfHabDirector = telfHabDirector;
       this.telfCelDirector = telfCelDirector;
       this.nombreCoordPio = nombreCoordPio;
       this.emailCoordPio = emailCoordPio;
       this.telfHabCoordPio = telfHabCoordPio;
       this.telfCelCoordPio = telfCelCoordPio;
       this.obsAAs = obsAAs;
       this.mencionPlantels = mencionPlantels;
       this.situacionEmbarazoses = situacionEmbarazoses;
       this.asistenciaInstitucions = asistenciaInstitucions;
       this.programasOrPses = programasOrPses;
       this.charlas = charlas;
       this.serviciosPlantels = serviciosPlantels;
       this.estudianteBachilleratos = estudianteBachilleratos;
       this.daniosInstitucions = daniosInstitucions;
    }
   
    public int getIdPlantel() {
        return this.idPlantel;
    }
    
    public void setIdPlantel(int idPlantel) {
        this.idPlantel = idPlantel;
    }
    public String getNombrePlantel() {
        return this.nombrePlantel;
    }
    
    public void setNombrePlantel(String nombrePlantel) {
        this.nombrePlantel = nombrePlantel;
    }
    public String getTipoInstitucion() {
        return this.tipoInstitucion;
    }
    
    public void setTipoInstitucion(String tipoInstitucion) {
        this.tipoInstitucion = tipoInstitucion;
    }
    public int getDistritoEscolar() {
        return this.distritoEscolar;
    }
    
    public void setDistritoEscolar(int distritoEscolar) {
        this.distritoEscolar = distritoEscolar;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmailPlantel() {
        return this.emailPlantel;
    }
    
    public void setEmailPlantel(String emailPlantel) {
        this.emailPlantel = emailPlantel;
    }
    public String getTlfPlantel() {
        return this.tlfPlantel;
    }
    
    public void setTlfPlantel(String tlfPlantel) {
        this.tlfPlantel = tlfPlantel;
    }
    public String getFaxPlantel() {
        return this.faxPlantel;
    }
    
    public void setFaxPlantel(String faxPlantel) {
        this.faxPlantel = faxPlantel;
    }
    public String getNombreDirector() {
        return this.nombreDirector;
    }
    
    public void setNombreDirector(String nombreDirector) {
        this.nombreDirector = nombreDirector;
    }
    public String getEmailDirector() {
        return this.emailDirector;
    }
    
    public void setEmailDirector(String emailDirector) {
        this.emailDirector = emailDirector;
    }
    public String getTelfHabDirector() {
        return this.telfHabDirector;
    }
    
    public void setTelfHabDirector(String telfHabDirector) {
        this.telfHabDirector = telfHabDirector;
    }
    public String getTelfCelDirector() {
        return this.telfCelDirector;
    }
    
    public void setTelfCelDirector(String telfCelDirector) {
        this.telfCelDirector = telfCelDirector;
    }
    public String getNombreCoordPio() {
        return this.nombreCoordPio;
    }
    
    public void setNombreCoordPio(String nombreCoordPio) {
        this.nombreCoordPio = nombreCoordPio;
    }
    public String getEmailCoordPio() {
        return this.emailCoordPio;
    }
    
    public void setEmailCoordPio(String emailCoordPio) {
        this.emailCoordPio = emailCoordPio;
    }
    public String getTelfHabCoordPio() {
        return this.telfHabCoordPio;
    }
    
    public void setTelfHabCoordPio(String telfHabCoordPio) {
        this.telfHabCoordPio = telfHabCoordPio;
    }
    public String getTelfCelCoordPio() {
        return this.telfCelCoordPio;
    }
    
    public void setTelfCelCoordPio(String telfCelCoordPio) {
        this.telfCelCoordPio = telfCelCoordPio;
    }
    public Set<ObsAA> getObsAAs() {
        return this.obsAAs;
    }
    
    public void setObsAAs(Set<ObsAA> obsAAs) {
        this.obsAAs = obsAAs;
    }
    public Set<MencionPlantel> getMencionPlantels() {
        return this.mencionPlantels;
    }
    
    public void setMencionPlantels(Set<MencionPlantel> mencionPlantels) {
        this.mencionPlantels = mencionPlantels;
    }
    public Set<SituacionEmbarazos> getSituacionEmbarazoses() {
        return this.situacionEmbarazoses;
    }
    
    public void setSituacionEmbarazoses(Set<SituacionEmbarazos> situacionEmbarazoses) {
        this.situacionEmbarazoses = situacionEmbarazoses;
    }
    public Set<AsistenciaInstitucion> getAsistenciaInstitucions() {
        return this.asistenciaInstitucions;
    }
    
    public void setAsistenciaInstitucions(Set<AsistenciaInstitucion> asistenciaInstitucions) {
        this.asistenciaInstitucions = asistenciaInstitucions;
    }
    public Set<ProgramasOrPs> getProgramasOrPses() {
        return this.programasOrPses;
    }
    
    public void setProgramasOrPses(Set<ProgramasOrPs> programasOrPses) {
        this.programasOrPses = programasOrPses;
    }
    public Set<Charla> getCharlas() {
        return this.charlas;
    }
    
    public void setCharlas(Set<Charla> charlas) {
        this.charlas = charlas;
    }
    public Set<ServiciosPlantel> getServiciosPlantels() {
        return this.serviciosPlantels;
    }
    
    public void setServiciosPlantels(Set<ServiciosPlantel> serviciosPlantels) {
        this.serviciosPlantels = serviciosPlantels;
    }
    public Set<EstudianteBachillerato> getEstudianteBachilleratos() {
        return this.estudianteBachilleratos;
    }
    
    public void setEstudianteBachilleratos(Set<EstudianteBachillerato> estudianteBachilleratos) {
        this.estudianteBachilleratos = estudianteBachilleratos;
    }
    public Set<DaniosInstitucion> getDaniosInstitucions() {
        return this.daniosInstitucions;
    }
    
    public void setDaniosInstitucions(Set<DaniosInstitucion> daniosInstitucions) {
        this.daniosInstitucions = daniosInstitucions;
    }




}


