package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * PlantelOtros generated by hbm2java
 */
public class PlantelOtros  implements java.io.Serializable {


     private int plantel;
     private String observacionesPlantaFisica;
     private int matricula;
     private int asistentesCharla;

    public PlantelOtros() {
    }

	
    public PlantelOtros(int plantel, int matricula, int asistentesCharla) {
        this.plantel = plantel;
        this.matricula = matricula;
        this.asistentesCharla = asistentesCharla;
    }
    public PlantelOtros(int plantel, String observacionesPlantaFisica, int matricula, int asistentesCharla) {
       this.plantel = plantel;
       this.observacionesPlantaFisica = observacionesPlantaFisica;
       this.matricula = matricula;
       this.asistentesCharla = asistentesCharla;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public String getObservacionesPlantaFisica() {
        return this.observacionesPlantaFisica;
    }
    
    public void setObservacionesPlantaFisica(String observacionesPlantaFisica) {
        this.observacionesPlantaFisica = observacionesPlantaFisica;
    }
    public int getMatricula() {
        return this.matricula;
    }
    
    public void setMatricula(int matricula) {
        this.matricula = matricula;
    }
    public int getAsistentesCharla() {
        return this.asistentesCharla;
    }
    
    public void setAsistentesCharla(int asistentesCharla) {
        this.asistentesCharla = asistentesCharla;
    }




}


