package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA



/**
 * ProgramasOrPs generated by hbm2java
 */
public class ProgramasOrPs  implements java.io.Serializable {


     private int plantel;
     private Plantel plantel_1;
     private char aplicacion;
     private char todosNiveles;
     private String cualesNiv;
     private char orientacion;
     private String cualesProg;
     private char instSinFl;
     private String cualesInst;

    public ProgramasOrPs() {
    }

    public ProgramasOrPs(int plantel, Plantel plantel_1, char aplicacion, char todosNiveles, String cualesNiv, char orientacion, String cualesProg, char instSinFl, String cualesInst) {
       this.plantel = plantel;
       this.plantel_1 = plantel_1;
       this.aplicacion = aplicacion;
       this.todosNiveles = todosNiveles;
       this.cualesNiv = cualesNiv;
       this.orientacion = orientacion;
       this.cualesProg = cualesProg;
       this.instSinFl = instSinFl;
       this.cualesInst = cualesInst;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public Plantel getPlantel_1() {
        return this.plantel_1;
    }
    
    public void setPlantel_1(Plantel plantel_1) {
        this.plantel_1 = plantel_1;
    }
    public char getAplicacion() {
        return this.aplicacion;
    }
    
    public void setAplicacion(char aplicacion) {
        this.aplicacion = aplicacion;
    }
    public char getTodosNiveles() {
        return this.todosNiveles;
    }
    
    public void setTodosNiveles(char todosNiveles) {
        this.todosNiveles = todosNiveles;
    }
    public String getCualesNiv() {
        return this.cualesNiv;
    }
    
    public void setCualesNiv(String cualesNiv) {
        this.cualesNiv = cualesNiv;
    }
    public char getOrientacion() {
        return this.orientacion;
    }
    
    public void setOrientacion(char orientacion) {
        this.orientacion = orientacion;
    }
    public String getCualesProg() {
        return this.cualesProg;
    }
    
    public void setCualesProg(String cualesProg) {
        this.cualesProg = cualesProg;
    }
    public char getInstSinFl() {
        return this.instSinFl;
    }
    
    public void setInstSinFl(char instSinFl) {
        this.instSinFl = instSinFl;
    }
    public String getCualesInst() {
        return this.cualesInst;
    }
    
    public void setCualesInst(String cualesInst) {
        this.cualesInst = cualesInst;
    }




}


