package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * SituacionEmbarazos generated by hbm2java
 */
public class SituacionEmbarazos  implements java.io.Serializable {


     private int plantel;
     private Plantel plantel_1;
     private int nroEmb;
     private Serializable edad;
     private Serializable nivel;

    public SituacionEmbarazos() {
    }

	
    public SituacionEmbarazos(int plantel, Plantel plantel_1, int nroEmb) {
        this.plantel = plantel;
        this.plantel_1 = plantel_1;
        this.nroEmb = nroEmb;
    }
    public SituacionEmbarazos(int plantel, Plantel plantel_1, int nroEmb, Serializable edad, Serializable nivel) {
       this.plantel = plantel;
       this.plantel_1 = plantel_1;
       this.nroEmb = nroEmb;
       this.edad = edad;
       this.nivel = nivel;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public Plantel getPlantel_1() {
        return this.plantel_1;
    }
    
    public void setPlantel_1(Plantel plantel_1) {
        this.plantel_1 = plantel_1;
    }
    public int getNroEmb() {
        return this.nroEmb;
    }
    
    public void setNroEmb(int nroEmb) {
        this.nroEmb = nroEmb;
    }
    public Serializable getEdad() {
        return this.edad;
    }
    
    public void setEdad(Serializable edad) {
        this.edad = edad;
    }
    public Serializable getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Serializable nivel) {
        this.nivel = nivel;
    }




}


