package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private String nombreUsuario;
     private String contrasenia;
     private Set<PerfilUsuario> perfilUsuarios = new HashSet<PerfilUsuario>(0);

    public Usuario() {
    }

	
    public Usuario(String nombreUsuario, String contrasenia) {
        this.nombreUsuario = nombreUsuario;
        this.contrasenia = contrasenia;
    }
    public Usuario(String nombreUsuario, String contrasenia, Set<PerfilUsuario> perfilUsuarios) {
       this.nombreUsuario = nombreUsuario;
       this.contrasenia = contrasenia;
       this.perfilUsuarios = perfilUsuarios;
    }
   
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public String getContrasenia() {
        return this.contrasenia;
    }
    
    public void setContrasenia(String contrasenia) {
        this.contrasenia = contrasenia;
    }
    public Set<PerfilUsuario> getPerfilUsuarios() {
        return this.perfilUsuarios;
    }
    
    public void setPerfilUsuarios(Set<PerfilUsuario> perfilUsuarios) {
        this.perfilUsuarios = perfilUsuarios;
    }




}


