package pio.hibernate;
// Generated 16/06/2011 03:01:40 PM by Hibernate Tools 3.2.1.GA


import java.io.Serializable;

/**
 * ViolenciaFisica generated by hbm2java
 */
public class ViolenciaFisica  implements java.io.Serializable {


     private int plantel;
     private char daniosFisicos;
     private String tiposDanios;
     private char armasBlancas;
     private char armasFuego;
     private char objetosContundentes;
     private String consecuencias;
     private Serializable nivel;
     private char agresoresAgredidos;
     private String acciones;
     private String causas;
     private Serializable sexo;
     private char seguridad;
     private String cuales;

    public ViolenciaFisica() {
    }

	
    public ViolenciaFisica(int plantel, char daniosFisicos, char armasBlancas, char armasFuego, char objetosContundentes, Serializable nivel, char agresoresAgredidos, char seguridad) {
        this.plantel = plantel;
        this.daniosFisicos = daniosFisicos;
        this.armasBlancas = armasBlancas;
        this.armasFuego = armasFuego;
        this.objetosContundentes = objetosContundentes;
        this.nivel = nivel;
        this.agresoresAgredidos = agresoresAgredidos;
        this.seguridad = seguridad;
    }
    public ViolenciaFisica(int plantel, char daniosFisicos, String tiposDanios, char armasBlancas, char armasFuego, char objetosContundentes, String consecuencias, Serializable nivel, char agresoresAgredidos, String acciones, String causas, Serializable sexo, char seguridad, String cuales) {
       this.plantel = plantel;
       this.daniosFisicos = daniosFisicos;
       this.tiposDanios = tiposDanios;
       this.armasBlancas = armasBlancas;
       this.armasFuego = armasFuego;
       this.objetosContundentes = objetosContundentes;
       this.consecuencias = consecuencias;
       this.nivel = nivel;
       this.agresoresAgredidos = agresoresAgredidos;
       this.acciones = acciones;
       this.causas = causas;
       this.sexo = sexo;
       this.seguridad = seguridad;
       this.cuales = cuales;
    }
   
    public int getPlantel() {
        return this.plantel;
    }
    
    public void setPlantel(int plantel) {
        this.plantel = plantel;
    }
    public char getDaniosFisicos() {
        return this.daniosFisicos;
    }
    
    public void setDaniosFisicos(char daniosFisicos) {
        this.daniosFisicos = daniosFisicos;
    }
    public String getTiposDanios() {
        return this.tiposDanios;
    }
    
    public void setTiposDanios(String tiposDanios) {
        this.tiposDanios = tiposDanios;
    }
    public char getArmasBlancas() {
        return this.armasBlancas;
    }
    
    public void setArmasBlancas(char armasBlancas) {
        this.armasBlancas = armasBlancas;
    }
    public char getArmasFuego() {
        return this.armasFuego;
    }
    
    public void setArmasFuego(char armasFuego) {
        this.armasFuego = armasFuego;
    }
    public char getObjetosContundentes() {
        return this.objetosContundentes;
    }
    
    public void setObjetosContundentes(char objetosContundentes) {
        this.objetosContundentes = objetosContundentes;
    }
    public String getConsecuencias() {
        return this.consecuencias;
    }
    
    public void setConsecuencias(String consecuencias) {
        this.consecuencias = consecuencias;
    }
    public Serializable getNivel() {
        return this.nivel;
    }
    
    public void setNivel(Serializable nivel) {
        this.nivel = nivel;
    }
    public char getAgresoresAgredidos() {
        return this.agresoresAgredidos;
    }
    
    public void setAgresoresAgredidos(char agresoresAgredidos) {
        this.agresoresAgredidos = agresoresAgredidos;
    }
    public String getAcciones() {
        return this.acciones;
    }
    
    public void setAcciones(String acciones) {
        this.acciones = acciones;
    }
    public String getCausas() {
        return this.causas;
    }
    
    public void setCausas(String causas) {
        this.causas = causas;
    }
    public Serializable getSexo() {
        return this.sexo;
    }
    
    public void setSexo(Serializable sexo) {
        this.sexo = sexo;
    }
    public char getSeguridad() {
        return this.seguridad;
    }
    
    public void setSeguridad(char seguridad) {
        this.seguridad = seguridad;
    }
    public String getCuales() {
        return this.cuales;
    }
    
    public void setCuales(String cuales) {
        this.cuales = cuales;
    }




}


